hw/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('shop_app.urls')),
    path('articles/', include('articles_app.urls')),
    path('', include('shop_app.urls', namespace='shop_app')),  #
    path('__debug__/', include('debug_toolbar.urls')),

]

shop_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'shop_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('order/', views.order_info, name='orders_info'),
    path('order/<int:client_id>/', views.all_orders, name='all_orders'),
    path('order/<int:client_id>/<str:period>/', views.orders_for_period, name='orders_for_period'),
    path('order/<int:client_id>/days/<int:days>/', views.orders_for_days, name='orders_for_days'),
    path('product/edit/<int:product_id>', views.edit_form, name='edit_form'),
    path('login/', views.CustomRegistrationView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.CustomRegistrationView.as_view(), name='signup'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My web-site{% endblock %}</title>
</head>
<body>
<header>
    {% if user.is_authenticated %}
    <div class="dropdown">
        <button class="btn btn-primary my-btn dropdown-toggle me-3" type="button"
                data-bs-toggle="dropdown" aria-expanded="false">
            {{ request.user }}
        </button>
        <ul class="dropdown-menu dd-color">
            <li>
                <a class="dropdown-item dd-item-color" href="{% url 'shop_app:logout' %}">Выйти</a>
            </li>
        </ul>
    </div>
    {% else %}
    <li class="nav-item">
        <a class="nav-link btn btn-primary my-btn me-3" href="{% url 'shop_app:login' %}">Войти</a>
    </li>
{% endif %}
</header>
    {% block content %}
    <p> Скоро тут появится текст...</p>
    {% endblock %}
    <br>
    <br>
    <br>
<p>Standard Text For All Pages</p>
</body>
</html>